name: pipe-extraction
channels:
  - conda-forge
dependencies:
  - python=3.13
  - numpy=2.3.3
  - pandas=2.3.3
  - laspy=2.6.1
  - scikit-learn=1.7.2
  - scikit-image=0.25.2
  - matplotlib=3.10.6
  - scipy=1.16.2

  # Webserver dependencies
  - fastapi=0.128.0
  - uvicorn=0.40.0
  - filelock=3.20.3
  - requests=2.32.5
